# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-07-01T12:45:19Z | model: claude-opus-4-8 via temper-skills | profile: standard | constraints: v1.0

def route_ticket(case: dict) -> str:
    priority = case.get('priority')
    security_score = case.get('security_score')
    customer_tier = case.get('customer_tier')
    category = case.get('category')
    sla_breached = case.get('sla_breached')

    # critic: hard constraint — overrides every routing rule below
    if security_score is not None and security_score > 0.95:
        return 'human_review'
    if category == "security" or (security_score is not None and security_score > 0.8):
        return 'escalate_security'
    # gray_zone: the 0.8 score threshold is a tuned cut — calibrate against your incident data
    # critic: urgent escalates regardless of tier — survived bad_faith_actor
    if priority == "urgent":
        return 'escalate_urgent'
    # critic: the priority×tier interaction the source prose only implied
    if priority == "high" and customer_tier in ("pro", "enterprise"):
        return 'escalate_urgent'
    # critic: sla×tier interaction — a breached SLA escalates only for paying tiers
    if sla_breached is True and customer_tier != "free":
        return 'escalate_urgent'
    if category == "billing":
        return 'route_billing'
    # critic: account/feature_request/other collapse into the default — not enumerated (overengineering_critic)
    if category == "bug":
        return 'route_engineering'
    return 'route_default'
