# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Behavior lock for route_ticket: each case asserts the tree's CURRENT output.
# Always green by construction — a failure here means the tree drifted (a real regression).
# Debates are NOT here; they live in the .validation.jsonl dataset.
import pytest
from route_ticket import route_ticket

# (input, tree_output, status, note)
LOCKED = [
    ({'priority': 'low', 'security_score': 0.99, 'customer_tier': 'free', 'category': 'bug', 'sla_breached': False}, 'human_review', 'ratified', 'ratified'),
    ({'priority': 'high', 'security_score': 0.85, 'customer_tier': 'pro', 'category': 'billing', 'sla_breached': False}, 'escalate_security', 'ratified', 'ratified'),
    ({'priority': 'medium', 'security_score': 0.1, 'customer_tier': 'enterprise', 'category': 'security', 'sla_breached': False}, 'escalate_security', 'ratified', 'ratified'),
    ({'priority': 'urgent', 'security_score': 0.1, 'customer_tier': 'free', 'category': 'feature_request', 'sla_breached': False}, 'escalate_urgent', 'ratified', 'ratified'),
    ({'priority': 'high', 'security_score': 0.2, 'customer_tier': 'enterprise', 'category': 'bug', 'sla_breached': False}, 'escalate_urgent', 'ratified', 'ratified'),
    ({'priority': 'high', 'security_score': 0.2, 'customer_tier': 'free', 'category': 'bug', 'sla_breached': False}, 'route_engineering', 'ratified', 'ratified'),
    ({'priority': 'medium', 'security_score': 0.2, 'customer_tier': 'pro', 'category': 'account', 'sla_breached': True}, 'escalate_urgent', 'ratified', 'ratified'),
    ({'priority': 'medium', 'security_score': 0.2, 'customer_tier': 'free', 'category': 'account', 'sla_breached': True}, 'route_default', 'ratified', 'ratified'),
    ({'priority': 'low', 'security_score': 0.2, 'customer_tier': 'enterprise', 'category': 'billing', 'sla_breached': False}, 'route_billing', 'ratified', 'ratified'),
    ({'priority': 'low', 'security_score': 0.1, 'customer_tier': 'free', 'category': 'bug', 'sla_breached': False}, 'route_engineering', 'ratified', 'ratified'),
    ({'priority': 'medium', 'security_score': 0.5, 'customer_tier': 'pro', 'category': 'feature_request', 'sla_breached': False}, 'route_default', 'ratified', 'ratified'),
    ({'priority': 'low', 'security_score': 0.1, 'customer_tier': 'free', 'category': 'other', 'sla_breached': False}, 'route_default', 'ratified', 'ratified'),
    ({'priority': 'urgent', 'security_score': 0.99, 'customer_tier': 'enterprise', 'category': 'security', 'sla_breached': True}, 'human_review', 'ratified', 'ratified'),
    ({'priority': 'high', 'security_score': 0.81, 'customer_tier': 'free', 'category': 'billing', 'sla_breached': False}, 'escalate_security', 'ratified', 'ratified'),
    ({'priority': 'medium', 'security_score': 0.79, 'customer_tier': 'enterprise', 'category': 'billing', 'sla_breached': False}, 'route_billing', 'ratified', 'ratified'),
    ({'priority': 'high', 'security_score': 0.2, 'customer_tier': 'pro', 'category': 'security', 'sla_breached': False}, 'escalate_security', 'ratified', 'ratified'),
    ({'priority': 'urgent', 'security_score': 0.2, 'customer_tier': 'enterprise', 'category': 'billing', 'sla_breached': True}, 'escalate_urgent', 'ratified', 'ratified'),
    ({'priority': 'low', 'security_score': None, 'customer_tier': 'free', 'category': 'bug', 'sla_breached': False}, 'route_engineering', 'ratified', 'ratified'),
]

@pytest.mark.parametrize("case,expected,status,note", LOCKED, ids=[c[3][:60] for c in LOCKED])
def test_route_ticket_behavior(case, expected, status, note):
    assert route_ticket(case) == expected
