# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Ratified-truth tests for route_ticket: assert the tree matches HUMAN-blessed labels.
# This file CAN fail — a red test here means the tree contradicts ratified ground truth.
# Comparison is leading-label (temper-skills' label_match): a descriptive outcome like
# 'no — toxic' honors the ratified label 'no'.
import pytest
from route_ticket import route_ticket

def _label(s):
    head = str(s).strip().split()[0] if str(s).strip() else ''
    return head.lower().rstrip(':,.—-')

# (input, ratified_label, note)
RATIFIED = [
    ({'priority': 'low', 'security_score': 0.99, 'customer_tier': 'free', 'category': 'bug', 'sla_breached': False}, 'human_review', 'ratified'),
    ({'priority': 'high', 'security_score': 0.85, 'customer_tier': 'pro', 'category': 'billing', 'sla_breached': False}, 'escalate_security', 'ratified'),
    ({'priority': 'medium', 'security_score': 0.1, 'customer_tier': 'enterprise', 'category': 'security', 'sla_breached': False}, 'escalate_security', 'ratified'),
    ({'priority': 'urgent', 'security_score': 0.1, 'customer_tier': 'free', 'category': 'feature_request', 'sla_breached': False}, 'escalate_urgent', 'ratified'),
    ({'priority': 'high', 'security_score': 0.2, 'customer_tier': 'enterprise', 'category': 'bug', 'sla_breached': False}, 'escalate_urgent', 'ratified'),
    ({'priority': 'high', 'security_score': 0.2, 'customer_tier': 'free', 'category': 'bug', 'sla_breached': False}, 'route_engineering', 'ratified'),
    ({'priority': 'medium', 'security_score': 0.2, 'customer_tier': 'pro', 'category': 'account', 'sla_breached': True}, 'escalate_urgent', 'ratified'),
    ({'priority': 'medium', 'security_score': 0.2, 'customer_tier': 'free', 'category': 'account', 'sla_breached': True}, 'route_default', 'ratified'),
    ({'priority': 'low', 'security_score': 0.2, 'customer_tier': 'enterprise', 'category': 'billing', 'sla_breached': False}, 'route_billing', 'ratified'),
    ({'priority': 'low', 'security_score': 0.1, 'customer_tier': 'free', 'category': 'bug', 'sla_breached': False}, 'route_engineering', 'ratified'),
    ({'priority': 'medium', 'security_score': 0.5, 'customer_tier': 'pro', 'category': 'feature_request', 'sla_breached': False}, 'route_default', 'ratified'),
    ({'priority': 'low', 'security_score': 0.1, 'customer_tier': 'free', 'category': 'other', 'sla_breached': False}, 'route_default', 'ratified'),
    ({'priority': 'urgent', 'security_score': 0.99, 'customer_tier': 'enterprise', 'category': 'security', 'sla_breached': True}, 'human_review', 'ratified'),
    ({'priority': 'high', 'security_score': 0.81, 'customer_tier': 'free', 'category': 'billing', 'sla_breached': False}, 'escalate_security', 'ratified'),
    ({'priority': 'medium', 'security_score': 0.79, 'customer_tier': 'enterprise', 'category': 'billing', 'sla_breached': False}, 'route_billing', 'ratified'),
    ({'priority': 'high', 'security_score': 0.2, 'customer_tier': 'pro', 'category': 'security', 'sla_breached': False}, 'escalate_security', 'ratified'),
    ({'priority': 'urgent', 'security_score': 0.2, 'customer_tier': 'enterprise', 'category': 'billing', 'sla_breached': True}, 'escalate_urgent', 'ratified'),
    ({'priority': 'low', 'security_score': None, 'customer_tier': 'free', 'category': 'bug', 'sla_breached': False}, 'route_engineering', 'ratified'),
]

@pytest.mark.parametrize("case,expected,note", RATIFIED, ids=[c[2][:60] for c in RATIFIED])
def test_route_ticket_ratified(case, expected, note):
    assert _label(route_ticket(case)) == _label(expected)
