# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-30T17:06:42Z | model: claude-opus-4-8 via claude-code-subagents | profile: standard | constraints: v1.0

def decide_walk(case: dict) -> str:
    hours_since_last_walk = case.get('hours_since_last_walk')
    weather = case.get('weather')
    dog_energy = case.get('dog_energy')
    owner_available = case.get('owner_available')
    is_late = case.get('is_late')

    if (weather or '').strip().lower() in ('storm', 'heat'):
        return 'toilet_break_only'
    # gray_zone: storm/heat wins even when the owner is unavailable or the walk is overdue — a toilet need can't be postponed; source leaves this precedence unstated.
    if owner_available is False and is_late is not True:
        return 'postpone_walk'
    # gray_zone: late + owner-unavailable falls through to a walk; source says don't postpone when late but never says who walks.
    if hours_since_last_walk is not None and hours_since_last_walk > 4 and (dog_energy or '').strip().lower() == 'high':
        return 'walk_now'
    return 'normal_walk'
