# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-29T13:57:10Z | model: vertex_ai/claude-sonnet-4-6 via api | profile: quick | constraints: v1.0
# quick profile — draft output, no provenance. Do not ship.

def decide_walk(case: dict) -> str:
    hours_since_last_walk = case.get('hours_since_last_walk')
    weather = case.get('weather')
    dog_energy = case.get('dog_energy')
    owner_available = case.get('owner_available')
    is_late = case.get('is_late')

    if ((weather or '').strip().lower() in ('storm', 'heat')):
        return 'toilet_break_only'
    if (owner_available is not None and owner_available == False) and (is_late is None or is_late == False):
        return 'postpone_walk'
    if hours_since_last_walk is not None and hours_since_last_walk >= 4 and (dog_energy or '').strip().lower() == 'high':
        return 'walk_now'
    if hours_since_last_walk is not None and hours_since_last_walk < 4:
        return 'no_walk_needed'
    return 'normal_walk'
