# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-30T17:06:42Z | model: claude-opus-4-8 via claude-code-subagents | profile: standard | constraints: v1.0

def decide_meal(case: dict) -> str:
    hours_since_last_meal = case.get('hours_since_last_meal')
    time_of_day = case.get('time_of_day')
    last_meal_size = case.get('last_meal_size')
    just_exercised = case.get('just_exercised')

    if just_exercised is True:
        return 'wait_then_full_meal'
    # gray_zone: schema has no minutes-since-exercise feature, so the 30-min rule can't be measured; any just_exercised case routes to rest-first-then-full. Checked first so it beats the evening-skip.
    if (time_of_day or '').strip().lower() == 'evening' and (last_meal_size or '').strip().lower() == 'full':
        return 'treat_only'
    # gray_zone: evening-skip wins even when the dog is overdue (hours >= 8); source rule 3 says skip in the evening if already fed full today.
    if hours_since_last_meal is not None and hours_since_last_meal >= 8:
        return 'full_meal'
    # critic: no explicit source rule for none+recent; collapsed in r1, restored in r2 after domain_expert showed light_meal under-feeds an empty stomach — endorsed by overengineering_critic r3.
    if (last_meal_size or '').strip().lower() == 'none':
        return 'full_meal'
    # gray_zone: ate nothing today -> a real meal, not the token light_meal default.
    return 'light_meal'
