# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-29T13:59:21Z | model: vertex_ai/claude-sonnet-4-6 via api | profile: quick | constraints: v1.0
# quick profile — draft output, no provenance. Do not ship.

def decide_meal(case: dict) -> str:
    hours_since_last_meal = case.get('hours_since_last_meal')
    time_of_day = case.get('time_of_day')
    last_meal_size = case.get('last_meal_size')
    just_exercised = case.get('just_exercised')

    if just_exercised == True and (time_of_day or '').strip().lower() == 'evening' and (last_meal_size or '').strip().lower() == 'full':
        return 'treat_only'
    if just_exercised == True and hours_since_last_meal is not None and hours_since_last_meal < 0.5:
        return 'skip_meal'
    if just_exercised == True and (hours_since_last_meal is None or hours_since_last_meal >= 0.5):
        return 'wait_then_full_meal'
    if (time_of_day or '').strip().lower() == 'evening' and (last_meal_size or '').strip().lower() == 'full':
        return 'treat_only'
    if hours_since_last_meal is not None and hours_since_last_meal < 8 and (last_meal_size or '').strip().lower() == 'none':
        return 'full_meal'
    if hours_since_last_meal is not None and hours_since_last_meal < 8 and (last_meal_size or '').strip().lower() == 'full':
        return 'light_meal'
    if hours_since_last_meal is not None and hours_since_last_meal >= 8:
        return 'full_meal'
    return 'light_meal'
