# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-29T14:03:26Z | model: vertex_ai/claude-sonnet-4-6 via api | profile: quick | constraints: v1.0
# quick profile — draft output, no provenance. Do not ship.

def decide_vet(case: dict) -> str:
    symptom = case.get('symptom')
    severity = case.get('severity')
    duration_hours = case.get('duration_hours')
    age_years = case.get('age_years')

    if severity is not None and (severity or '').strip().lower() == 'severe':
        return 'vet_urgent'
    if symptom is not None and (symptom or '').strip().lower() == 'none':
        return 'monitor_home'
    if duration_hours is not None and duration_hours >= 48:
        return 'vet_soon'
    if age_years is not None and (age_years < 1 or age_years > 8) and symptom is not None and (symptom or '').strip().lower() != 'none':
        return 'vet_call'
    return 'monitor_home'
