# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-07-01T05:52:00Z | model: claude-opus-4-8 via claude-code-subagents | profile: standard | constraints: v1.0

def decide_meal(case: dict) -> str:
    hours_since_last_meal = case.get('hours_since_last_meal')
    time_of_day = case.get('time_of_day')
    last_meal_size = case.get('last_meal_size')
    just_exercised = case.get('just_exercised')
    minutes_since_exercise = case.get('minutes_since_exercise')
    had_full_meal_today = case.get('had_full_meal_today')

    # critic: Placed above the exercise rules so an already-fully-fed evening dog never gets a second full meal (edge_case_hunter/domain_expert r1); edge_case_hunter's r2 swap to wait_then_full_meal was rejected — it re-breaks the cap.
    if (time_of_day or '').strip().lower() == 'evening' and (had_full_meal_today is True or (had_full_meal_today is None and (last_meal_size or '').strip().lower() == 'full')):
        return 'treat_only'
    # gray_zone: Evening skip keys on the whole-day had_full_meal_today (added via schema re-gate r1); last_meal_size=='full' is only the fallback when the flag is None. Overlap case [evening + already_full + just_exercised + minutes<30] resolves to treat_only, not wait_then_full_meal, because promising a full meal would violate the 'a treat at most' cap — the four-outcome set can't say 'wait, then a treat', so offer the treat once the dog settles.
    if just_exercised is True and (minutes_since_exercise is None or minutes_since_exercise < 30):
        return 'wait_then_full_meal'
    # gray_zone: Within 30 min of exercise (or unknown timing) rest first; None minutes_since_exercise is treated as still-resting (conservative, honors 'never feed within 30 min').
    if just_exercised is True:
        return 'full_meal'
    # gray_zone: just_exercised is the governing exercise predicate; a stale minutes_since_exercise with just_exercised False is correctly ignored.
    if hours_since_last_meal is not None and hours_since_last_meal >= 8:
        return 'full_meal'
    if (last_meal_size or '').strip().lower() == 'none':
        return 'full_meal'
    # gray_zone: Ate nothing today -> a real meal, not the token light_meal default.
    return 'light_meal'
