# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Behavior lock for decide_walk: each case asserts the frozen tree's current output.
# Cases are panel-built proposals unless marked 'ratified'; see notes for provenance.
import pytest
from decide_walk import decide_walk

# (input, expected_output, status, note)
LOCKED = [
    ({'weather': 'storm', 'dog_energy': 'high', 'hours_since_last_walk': 6, 'owner_available': False, 'is_late': False}, 'toilet_break_only', 'resolved', "edge_case_hunter#r1 — RESOLVED (proposer, no domain oracle): chose toilet_break_only over edge_case_hunter's postpone_walk — weather is a safety floor, a toilet need can't be postponed."),
    ({'weather': 'heat', 'dog_energy': 'normal', 'hours_since_last_walk': 1, 'owner_available': False, 'is_late': False}, 'toilet_break_only', 'resolved', 'edge_case_hunter#r1 — RESOLVED (proposer): same precedence in heat — toilet_break_only over postpone_walk.'),
    ({'weather': 'heat', 'owner_available': False, 'is_late': False}, 'toilet_break_only', 'proposed', "domain_expert#r1 — Heat is a safety floor; a toilet need can't be postponed."),
    ({'weather': 'storm', 'owner_available': False, 'hours_since_last_walk': 6, 'dog_energy': 'high'}, 'toilet_break_only', 'proposed', 'domain_expert#r1 — Storm beats both the overdue-walk and postpone rules.'),
    ({'weather': 'clear', 'dog_energy': 'high', 'hours_since_last_walk': 6, 'owner_available': False, 'is_late': True}, 'walk_now', 'proposed', 'edge_case_hunter#r2,domain_expert#r2 — Late + unavailable must not postpone; overdue high-energy still walks now.'),
    ({'weather': 'clear', 'dog_energy': None, 'hours_since_last_walk': None, 'owner_available': None, 'is_late': None}, 'normal_walk', 'proposed', 'edge_case_hunter#r2 — All-None non-weather features degrade safely to normal_walk.'),
    ({'weather': 'clear', 'dog_energy': 'high', 'hours_since_last_walk': 6, 'owner_available': False, 'is_late': False}, 'postpone_walk', 'proposed', 'domain_expert#r2 — Owner unavailable and not late must postpone, even when overdue with high energy.'),
    ({'hours_since_last_walk': 2, 'weather': 'rain', 'dog_energy': 'normal', 'owner_available': True, 'is_late': False}, 'normal_walk', 'proposed', 'domain_expert#r2 — Rain is not a storm; a non-overdue normal dog gets a normal walk.'),
]

@pytest.mark.parametrize("case,expected,status,note", LOCKED, ids=[c[3][:60] for c in LOCKED])
def test_decide_walk_behavior(case, expected, status, note):
    assert decide_walk(case) == expected
