# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Behavior lock for decide_vet: each case asserts the tree's CURRENT output.
# Always green by construction — a failure here means the tree drifted (a real regression).
# Debates are NOT here; they live in the .validation.jsonl dataset.
import pytest
from decide_vet import decide_vet

# (input, tree_output, status, note)
LOCKED = [
    ({'symptom': 'lethargy', 'severity': 'mild', 'duration_hours': 24, 'age_years': 4}, 'vet_call', 'proposed', 'edge_case_hunter#r1 — Exactly 24h mild adult: not brief, not >=48 -> escalates rather than monitoring.'),
    ({'symptom': 'limping', 'severity': 'moderate', 'duration_hours': 2, 'age_years': 4}, 'vet_call', 'proposed', 'edge_case_hunter#r1 — Moderate brief adult falls to the conservative default.'),
    ({'symptom': 'vomiting', 'severity': 'mild', 'duration_hours': 2, 'age_years': 9}, 'vet_call', 'proposed', 'edge_case_hunter#r1 — Senior with mild brief symptom escalates via age>8 before the monitor branch.'),
    ({'symptom': 'limping', 'severity': 'moderate', 'duration_hours': 30, 'age_years': 5}, 'vet_call', 'proposed', 'domain_expert#r1 — Moderate adult below 48h falls to safe default rather than under-referring.'),
    ({'symptom': 'lethargy', 'severity': 'mild', 'duration_hours': 1, 'age_years': 11}, 'vet_call', 'proposed', 'domain_expert#r1 — Senior with trivial brief symptom gets the lower threshold.'),
    ({'symptom': 'not_eating', 'severity': 'mild', 'duration_hours': None, 'age_years': 4}, 'vet_call', 'proposed', 'domain_expert#r1 — Unknown duration on a real symptom escalates safely instead of monitoring.'),
    ({'symptom': 'vomiting', 'severity': 'mild', 'duration_hours': -5, 'age_years': 3}, 'vet_call', 'proposed', 'edge_case_hunter#r2 — Negative duration is invalid; the 0<= guard prevents a falsely reassuring monitor_home.'),
    ({'symptom': 'limping', 'severity': 'mild', 'duration_hours': 0, 'age_years': 4}, 'monitor_home', 'proposed', 'edge_case_hunter#r2 — Zero-hour mild symptom is the genuine brief case; documents the boundary vs negatives.'),
    ({'symptom': 'vomiting', 'severity': 'severe', 'duration_hours': None, 'age_years': None}, 'vet_urgent', 'proposed', 'edge_case_hunter#r2 — Severe wins regardless of missing duration/age.'),
    ({'symptom': 'lethargy', 'severity': 'moderate', 'duration_hours': 60, 'age_years': 11}, 'vet_soon', 'resolved', 'domain_expert#r2 — RESOLVED (proposer): chose vet_soon over vet_call — the source ranks soon > call, so crossing 48h escalates the senior, not downgrades.'),
    ({'symptom': 'vomiting', 'severity': 'moderate', 'duration_hours': 72, 'age_years': 0.5}, 'vet_soon', 'resolved', 'domain_expert#r2 — RESOLVED (proposer): same ranking call for a puppy — vet_soon over vet_call.'),
    ({'symptom': 'limping', 'severity': 'severe', 'duration_hours': 2, 'age_years': 10}, 'vet_urgent', 'proposed', 'domain_expert#r2 — Severe short-circuits to urgent before age for a senior.'),
    ({'symptom': 'limping', 'severity': 'moderate', 'duration_hours': 36, 'age_years': 4}, 'vet_call', 'proposed', 'edge_case_hunter#r3 — Moderate persisted past brief window but under 48h on an adult -> vet_call.'),
    ({'symptom': 'vomiting', 'severity': None, 'duration_hours': 3, 'age_years': 5}, 'vet_call', 'proposed', 'domain_expert#r3 — Unknown severity with a real symptom must not be downgraded to monitor_home.'),
]

@pytest.mark.parametrize("case,expected,status,note", LOCKED, ids=[c[3][:60] for c in LOCKED])
def test_decide_vet_behavior(case, expected, status, note):
    assert decide_vet(case) == expected
