# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Behavior lock for decide_walk: each case asserts the tree's CURRENT output.
# Always green by construction — a failure here means the tree drifted (a real regression).
# Debates are NOT here; they live in the .validation.jsonl dataset.
import pytest
from decide_walk import decide_walk

# (input, tree_output, status, note)
LOCKED = [
    ({'hours_since_last_walk': 6, 'weather': 'heat', 'temperature_c': 12, 'dog_energy': 'high', 'owner_available': True, 'is_late': False}, 'walk_now', 'proposed', "edge_case_hunter#r1 — Measured 12°C is below the 30°C danger threshold, so the 'heat' label must NOT trip the skip; overdue + high energy walks now."),
    ({'hours_since_last_walk': 2, 'weather': 'heat', 'temperature_c': 18, 'dog_energy': 'normal', 'owner_available': True, 'is_late': False}, 'normal_walk', 'proposed', "edge_case_hunter#r1 — A measured moderate temperature under 30°C overrides the categorical 'heat' label; normal walkable day."),
    ({'hours_since_last_walk': 2, 'weather': 'clear', 'temperature_c': 35, 'dog_energy': 'normal', 'owner_available': True, 'is_late': False}, 'toilet_break_only', 'proposed', "domain_expert#r2 — Unlabeled heat wave: 35°C with weather='clear' must fire the >30°C skip via the measured field."),
    ({'hours_since_last_walk': 6, 'weather': 'heat', 'temperature_c': 28, 'dog_energy': 'high', 'owner_available': True, 'is_late': False}, 'walk_now', 'proposed', "domain_expert#r2 — 'heat' label but only 28°C (present, ≤30): numeric temperature overrides an alarming label; overdue+high → walk_now."),
    ({'hours_since_last_walk': 6, 'weather': 'storm', 'temperature_c': None, 'dog_energy': 'high', 'owner_available': False, 'is_late': False}, 'toilet_break_only', 'proposed', 'domain_expert#r1 — Storm beats both the overdue-walk and the postpone rules.'),
    ({'hours_since_last_walk': 1, 'weather': 'heat', 'temperature_c': None, 'dog_energy': 'normal', 'owner_available': False, 'is_late': False}, 'toilet_break_only', 'proposed', "edge_case_hunter#r1 — 'heat' label with unmeasured temperature falls back to the safety skip; a toilet need can't be postponed."),
    ({'hours_since_last_walk': 6, 'weather': 'clear', 'temperature_c': None, 'dog_energy': 'high', 'owner_available': False, 'is_late': True}, 'walk_now', 'proposed', 'edge_case_hunter#r2 — Late + unavailable must not postpone; overdue high-energy still walks now.'),
    ({'hours_since_last_walk': None, 'weather': 'clear', 'temperature_c': None, 'dog_energy': None, 'owner_available': None, 'is_late': None}, 'normal_walk', 'proposed', 'edge_case_hunter#r2 — All-None non-weather features degrade safely to normal_walk without raising.'),
    ({'hours_since_last_walk': 6, 'weather': 'clear', 'temperature_c': None, 'dog_energy': 'high', 'owner_available': False, 'is_late': False}, 'postpone_walk', 'proposed', 'domain_expert#r2 — Owner unavailable and not late must postpone, even when overdue with high energy.'),
    ({'hours_since_last_walk': 2, 'weather': 'rain', 'temperature_c': None, 'dog_energy': 'normal', 'owner_available': True, 'is_late': False}, 'normal_walk', 'proposed', 'domain_expert#r2 — Rain is not a storm; a non-overdue normal dog gets a normal walk.'),
    ({'hours_since_last_walk': 6, 'weather': 'snow', 'temperature_c': -8, 'dog_energy': 'high', 'owner_available': True, 'is_late': False}, 'walk_now', 'proposed', 'domain_expert#r2 — Source is silent on snow/cold: no branch, so an overdue high-energy dog still walks now (documented gray zone — no cold threshold exists).'),
]

@pytest.mark.parametrize("case,expected,status,note", LOCKED, ids=[c[3][:60] for c in LOCKED])
def test_decide_walk_behavior(case, expected, status, note):
    assert decide_walk(case) == expected
