# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Behavior lock for decide_meal: each case asserts the frozen tree's current output.
# Cases are panel-built proposals unless marked 'ratified'; see notes for provenance.
import pytest
from decide_meal import decide_meal

# (input, expected_output, status, note)
LOCKED = [
    ({'time_of_day': 'evening', 'last_meal_size': 'full', 'just_exercised': True, 'hours_since_last_meal': 5}, 'wait_then_full_meal', 'proposed', 'edge_case_hunter#r1 — Post-exercise rest-then-feed must beat the evening skip; never serve right after vigorous exercise.'),
    ({'time_of_day': 'evening', 'last_meal_size': 'full', 'just_exercised': False, 'hours_since_last_meal': 5}, 'treat_only', 'proposed', 'edge_case_hunter#r1 — Without exercise the evening-skip correctly applies.'),
    ({'time_of_day': 'evening', 'last_meal_size': 'none', 'just_exercised': True, 'hours_since_last_meal': 13}, 'wait_then_full_meal', 'proposed', 'domain_expert#r1 — Evening starving dog that just exercised should rest then get a full meal.'),
    ({'time_of_day': 'evening', 'last_meal_size': 'full', 'just_exercised': False, 'hours_since_last_meal': 11}, 'treat_only', 'proposed', 'edge_case_hunter#r2 — Gray-zone ratify: evening-skip intentionally wins over the 8-12h feeding floor when already fed full.'),
    ({'time_of_day': 'midday', 'last_meal_size': 'full', 'just_exercised': False, 'hours_since_last_meal': 11}, 'full_meal', 'proposed', 'edge_case_hunter#r2 — Same overdue+full but non-evening: the feeding floor applies, full_meal.'),
    ({'time_of_day': 'evening', 'last_meal_size': 'none', 'just_exercised': False, 'hours_since_last_meal': 4}, 'full_meal', 'proposed', 'domain_expert#r2 — Drove the none->full fix: a dog that ate nothing today gets a real meal, not light.'),
    ({'time_of_day': 'midday', 'last_meal_size': 'light', 'just_exercised': False, 'hours_since_last_meal': 3}, 'light_meal', 'resolved', "domain_expert#r3 — RESOLVED (proposer): chose light_meal over domain_expert's full_meal — a full meal 3h after a light one violates the 8-12h feeding interval."),
    ({'time_of_day': 'midday', 'last_meal_size': 'full', 'just_exercised': False, 'hours_since_last_meal': 3}, 'light_meal', 'proposed', 'domain_expert#r3 — Rule 4 canonical: last meal full and recent -> light_meal.'),
    ({'time_of_day': 'midday', 'last_meal_size': 'none', 'just_exercised': False, 'hours_since_last_meal': 1}, 'full_meal', 'proposed', 'domain_expert#r3 — Regression guard: the none->full fix still holds for a recent empty stomach.'),
    ({'hours_since_last_meal': None, 'time_of_day': None, 'last_meal_size': None, 'just_exercised': None}, 'light_meal', 'proposed', 'edge_case_hunter#r3 — All-None must not crash and yields the conservative light_meal default.'),
]

@pytest.mark.parametrize("case,expected,status,note", LOCKED, ids=[c[3][:60] for c in LOCKED])
def test_decide_meal_behavior(case, expected, status, note):
    assert decide_meal(case) == expected
