# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Behavior lock for decide_meal: each case asserts the tree's CURRENT output.
# Always green by construction — a failure here means the tree drifted (a real regression).
# Debates are NOT here; they live in the .validation.jsonl dataset.
import pytest
from decide_meal import decide_meal

# (input, tree_output, status, note)
LOCKED = [
    ({'hours_since_last_meal': 3, 'time_of_day': 'evening', 'last_meal_size': 'full', 'just_exercised': True, 'minutes_since_exercise': 45, 'had_full_meal_today': True}, 'treat_only', 'proposed', "domain_expert#r2 — Rested after an evening walk but already had the day's full meal: the evening cap wins, only a treat — never a second full meal."),
    ({'hours_since_last_meal': 4, 'time_of_day': 'evening', 'last_meal_size': 'full', 'just_exercised': True, 'minutes_since_exercise': 45, 'had_full_meal_today': None}, 'treat_only', 'proposed', "edge_case_hunter#r1 — had_full_meal_today unknown falls back to last_meal_size=='full'; still capped to a treat post-exercise."),
    ({'hours_since_last_meal': 5, 'time_of_day': 'evening', 'last_meal_size': 'full', 'just_exercised': False, 'minutes_since_exercise': None, 'had_full_meal_today': True}, 'treat_only', 'proposed', 'edge_case_hunter#r1 — Plain evening skip: already had a full meal today.'),
    ({'hours_since_last_meal': 13, 'time_of_day': 'evening', 'last_meal_size': 'none', 'just_exercised': True, 'minutes_since_exercise': None, 'had_full_meal_today': False}, 'wait_then_full_meal', 'proposed', 'domain_expert#r1 — Starving evening dog that just exercised (unknown timing) rests first, then a full meal — evening cap does not apply (no full meal today).'),
    ({'hours_since_last_meal': 11, 'time_of_day': 'evening', 'last_meal_size': 'full', 'just_exercised': False, 'minutes_since_exercise': None, 'had_full_meal_today': True}, 'treat_only', 'proposed', 'edge_case_hunter#r2 — Evening cap intentionally wins over the 8-12h feeding floor when already fed full today.'),
    ({'hours_since_last_meal': 11, 'time_of_day': 'midday', 'last_meal_size': 'full', 'just_exercised': False, 'minutes_since_exercise': None, 'had_full_meal_today': True}, 'full_meal', 'proposed', 'edge_case_hunter#r2 — Same overdue+full but non-evening: the feeding floor applies, full_meal.'),
    ({'hours_since_last_meal': 2, 'time_of_day': 'morning', 'last_meal_size': 'light', 'just_exercised': True, 'minutes_since_exercise': 40, 'had_full_meal_today': False}, 'full_meal', 'proposed', 'domain_expert#r2 — Exercised and rested >=30 min, not yet full today: the fuller post-exercise meal.'),
    ({'hours_since_last_meal': 4, 'time_of_day': 'evening', 'last_meal_size': 'none', 'just_exercised': False, 'minutes_since_exercise': None, 'had_full_meal_today': False}, 'full_meal', 'proposed', 'domain_expert#r2 — A dog that ate nothing today gets a real meal, not light.'),
    ({'hours_since_last_meal': 3, 'time_of_day': 'midday', 'last_meal_size': 'light', 'just_exercised': False, 'minutes_since_exercise': None, 'had_full_meal_today': False}, 'light_meal', 'proposed', 'domain_expert#r3 — A full meal 3h after a light one would violate the 8-12h interval; light_meal.'),
    ({'hours_since_last_meal': 3, 'time_of_day': 'midday', 'last_meal_size': 'full', 'just_exercised': False, 'minutes_since_exercise': None, 'had_full_meal_today': True}, 'light_meal', 'proposed', 'domain_expert#r3 — Rule 4 canonical: last meal full and recent -> light_meal (non-evening, so no cap).'),
    ({'hours_since_last_meal': 1, 'time_of_day': 'midday', 'last_meal_size': 'none', 'just_exercised': False, 'minutes_since_exercise': None, 'had_full_meal_today': False}, 'full_meal', 'proposed', 'domain_expert#r3 — Regression guard: the none->full base case holds for a recent empty stomach.'),
    ({'hours_since_last_meal': None, 'time_of_day': None, 'last_meal_size': None, 'just_exercised': None, 'minutes_since_exercise': None, 'had_full_meal_today': None}, 'light_meal', 'proposed', 'edge_case_hunter#r3 — All-None must not crash and yields the conservative light_meal default.'),
    ({'hours_since_last_meal': 2, 'time_of_day': 'evening', 'last_meal_size': 'full', 'just_exercised': True, 'minutes_since_exercise': 10, 'had_full_meal_today': True}, 'treat_only', 'proposed', "edge_case_hunter#r2 — CONTESTED: edge_case_hunter argues a treat within 30 min of exercise violates 'never feed within 30 min'; the arbiter chose treat_only instead (a forbidden 2nd full meal is worse). Open dispute."),
    ({'hours_since_last_meal': 3, 'time_of_day': 'evening', 'last_meal_size': 'full', 'just_exercised': True, 'minutes_since_exercise': 5, 'had_full_meal_today': None}, 'treat_only', 'proposed', 'edge_case_hunter#r2 — CONTESTED (fallback path): same 30-min objection via had_full_meal_today=None; arbiter kept treat_only. Open dispute.'),
]

@pytest.mark.parametrize("case,expected,status,note", LOCKED, ids=[c[3][:60] for c in LOCKED])
def test_decide_meal_behavior(case, expected, status, note):
    assert decide_meal(case) == expected
