# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-29T16:39:01Z | model: claude-sonnet-4-6 via temper-skills | profile: standard | constraints: v1.0

def can_i_park(case: dict) -> str:
    zone_type = case.get('zone_type')
    day = case.get('day')
    hour = case.get('hour')
    is_public_holiday = case.get('is_public_holiday')
    has_resident_permit = case.get('has_resident_permit')

    # n1 — survived 6 rounds — sources: skill.md, constraints#precedence — critic: no_stopping beats everything — checked first, no exemption for holiday/permit/hour
    if (zone_type or '').strip().lower() == 'no_stopping':
        return 'prohibited'
    # n2 — survived 5 rounds — sources: skill.md, constraints#precedence — critic: active street-cleaning window beats meter/permit rules and applies to every zone; a resident permit does NOT exempt it
    if (day or '').strip().lower() in ('tuesday', 'friday') and hour is not None and 11 <= hour < 13 and not is_public_holiday:
        return 'no_parking_street_cleaning'
    # gray_zone: Suspended on public holidays (is_public_holiday true falls through). Window is the clock hours 11 and 12 (>=11 and <13).
    # n3 — survived 4 rounds — sources: skill.md — critic: meter enforced Mon-Sat 09:00-18:00 on non-holidays; pay, 2-hour limit
    if (zone_type or '').strip().lower() == 'metered' and (day or '').strip().lower() != 'sunday' and not is_public_holiday and hour is not None and 9 <= hour < 18:
        return 'pay_and_display_2h'
    # gray_zone: The 2-hour cap can't be enforced by the tree alone; a downstream system must track elapsed duration.
    # n4 — survived 4 rounds — sources: skill.md — critic: metered but outside enforcement — Sunday, public holiday, or before 09:00 / from 18:00 — meter is free
    if (zone_type or '').strip().lower() == 'metered':
        return 'free'
    # n5 — survived 3 rounds — sources: skill.md — critic: permit enforced Mon-Fri 08:00-20:00 on non-holidays; no permit -> not allowed
    if (zone_type or '').strip().lower() == 'residential_permit' and (day or '').strip().lower() in ('monday', 'tuesday', 'wednesday', 'thursday', 'friday') and not is_public_holiday and hour is not None and 8 <= hour < 20 and not has_resident_permit:
        return 'permit_required'
    # n6 — survived 4 rounds — sources: skill.md — critic: residential block open to all: permit holder during enforcement, or anyone off-hours / weekend / holiday
    if (zone_type or '').strip().lower() == 'residential_permit':
        return 'free'
    # n7 — survived 6 rounds — sources: skill.md
    if (zone_type or '').strip().lower() == 'unrestricted':
        return 'free'
    return 'prohibited'
