# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Behavior lock for assess_ankle: each case asserts the tree's CURRENT output.
# Always green by construction — a failure here means the tree drifted (a real regression).
# Debates are NOT here; they live in the .validation.jsonl dataset.
import pytest
from assess_ankle import assess_ankle

# (input, tree_output, status, note)
LOCKED = [
    ({'pain_malleolar_zone': False, 'visible_deformity': True, 'can_bear_weight': False, 'sprain_grade': 'severe', 'hours_since_injury': 1, 'age_years': 30}, 'urgent_care', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': True, 'bone_tenderness_lateral_malleolus': True, 'can_bear_weight': True, 'sprain_grade': 'moderate', 'hours_since_injury': 5, 'age_years': 30}, 'seek_imaging', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': False, 'sprain_grade': 'moderate', 'hours_since_injury': 3, 'age_years': 30}, 'seek_imaging', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': False, 'can_bear_weight': False, 'sprain_grade': 'moderate', 'hours_since_injury': 3, 'age_years': 30}, 'see_clinician', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 6, 'age_years': 60}, 'see_clinician', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': False, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 6, 'age_years': 12}, 'see_clinician', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': True, 'sprain_grade': 'severe', 'hours_since_injury': 6, 'age_years': 30}, 'see_clinician', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 10, 'age_years': 30}, 'police_acute', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': False, 'can_bear_weight': True, 'sprain_grade': 'moderate', 'hours_since_injury': 120, 'age_years': 40}, 'police_subacute', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': None, 'age_years': 30}, 'see_clinician', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': True, 'bone_tenderness_medial_malleolus': True, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 4, 'age_years': 30}, 'seek_imaging', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': True, 'bone_tenderness_lateral_malleolus': False, 'bone_tenderness_medial_malleolus': False, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 8, 'age_years': 35}, 'police_acute', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': False, 'can_bear_weight': True, 'sprain_grade': 'moderate', 'hours_since_injury': 24, 'age_years': 28, 'patient_profile': 'active'}, 'police_acute', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': False, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 200, 'age_years': 45, 'patient_profile': 'sedentary'}, 'police_subacute', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': False, 'visible_deformity': True, 'sprain_grade': 'severe', 'hours_since_injury': 1, 'age_years': 30}, 'urgent_care', 'ratified', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': True, 'sprain_grade': 'moderate', 'hours_since_injury': 50, 'age_years': 50}, 'police_acute', 'ratified', 'ratified'),
]

@pytest.mark.parametrize("case,expected,status,note", LOCKED, ids=[c[3][:60] for c in LOCKED])
def test_assess_ankle_behavior(case, expected, status, note):
    assert assess_ankle(case) == expected
