# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Ratified-truth tests for assess_ankle: assert the tree matches HUMAN-blessed labels.
# This file CAN fail — a red test here means the tree contradicts ratified ground truth.
# Comparison is leading-label (temper-skills' label_match): a descriptive outcome like
# 'no — toxic' honors the ratified label 'no'.
import pytest
from assess_ankle import assess_ankle

def _label(s):
    head = str(s).strip().split()[0] if str(s).strip() else ''
    return head.lower().rstrip(':,.—-')

# (input, ratified_label, note)
RATIFIED = [
    ({'pain_malleolar_zone': False, 'visible_deformity': True, 'can_bear_weight': False, 'sprain_grade': 'severe', 'hours_since_injury': 1, 'age_years': 30}, 'urgent_care', 'ratified'),
    ({'pain_malleolar_zone': True, 'bone_tenderness_lateral_malleolus': True, 'can_bear_weight': True, 'sprain_grade': 'moderate', 'hours_since_injury': 5, 'age_years': 30}, 'seek_imaging', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': False, 'sprain_grade': 'moderate', 'hours_since_injury': 3, 'age_years': 30}, 'seek_imaging', 'ratified'),
    ({'pain_malleolar_zone': False, 'can_bear_weight': False, 'sprain_grade': 'moderate', 'hours_since_injury': 3, 'age_years': 30}, 'see_clinician', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 6, 'age_years': 60}, 'see_clinician', 'ratified'),
    ({'pain_malleolar_zone': False, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 6, 'age_years': 12}, 'see_clinician', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': True, 'sprain_grade': 'severe', 'hours_since_injury': 6, 'age_years': 30}, 'see_clinician', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 10, 'age_years': 30}, 'police_acute', 'ratified'),
    ({'pain_malleolar_zone': False, 'can_bear_weight': True, 'sprain_grade': 'moderate', 'hours_since_injury': 120, 'age_years': 40}, 'police_subacute', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': None, 'age_years': 30}, 'see_clinician', 'ratified'),
    ({'pain_malleolar_zone': True, 'bone_tenderness_medial_malleolus': True, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 4, 'age_years': 30}, 'seek_imaging', 'ratified'),
    ({'pain_malleolar_zone': True, 'bone_tenderness_lateral_malleolus': False, 'bone_tenderness_medial_malleolus': False, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 8, 'age_years': 35}, 'police_acute', 'ratified'),
    ({'pain_malleolar_zone': False, 'can_bear_weight': True, 'sprain_grade': 'moderate', 'hours_since_injury': 24, 'age_years': 28, 'patient_profile': 'active'}, 'police_acute', 'ratified'),
    ({'pain_malleolar_zone': False, 'can_bear_weight': True, 'sprain_grade': 'mild', 'hours_since_injury': 200, 'age_years': 45, 'patient_profile': 'sedentary'}, 'police_subacute', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': False, 'visible_deformity': True, 'sprain_grade': 'severe', 'hours_since_injury': 1, 'age_years': 30}, 'urgent_care', 'ratified'),
    ({'pain_malleolar_zone': True, 'can_bear_weight': True, 'sprain_grade': 'moderate', 'hours_since_injury': 50, 'age_years': 50}, 'police_acute', 'ratified'),
]

@pytest.mark.parametrize("case,expected,note", RATIFIED, ids=[c[2][:60] for c in RATIFIED])
def test_assess_ankle_ratified(case, expected, note):
    assert _label(assess_ankle(case)) == _label(expected)
