# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-28T19:42:36Z | model: claude-opus-4-8 via temper-skills | profile: audit-grade | constraints: v1.0

def assess_license(case: dict) -> str:
    project_license = case.get('project_license')
    dependency_license = case.get('dependency_license')
    linking = case.get('linking')
    distributing = case.get('distributing')
    modified_dependency = case.get('modified_dependency')

    # n1 — survived 16 rounds — sources: domain_expert, examples#5 — critic: distribution gates every obligation — checked first; survived 16 rounds
    if distributing is not True:
        return 'ok_internal_use'
    # n2 — survived 14 rounds — sources: domain_expert — critic: AGPL's source obligation reaches even mere-aggregation / network use
    if dependency_license == 'AGPL-3.0':
        return 'must_offer_source'
    # gray_zone: network-use scope is fact-specific — confirm deployment model
    # n3 — survived 13 rounds — sources: domain_expert, edge_case_hunter, examples#2 — critic: the license×linking×distribution interaction: copyleft propagates only when linked AND distributed into a non-GPL project
    if dependency_license in ('GPL-2.0', 'GPL-3.0') and linking != 'none' and project_license in ('MIT', 'BSD-3-Clause', 'Apache-2.0', 'proprietary', 'LGPL-3.0', 'MPL-2.0'):
        return 'project_must_be_gpl'
    # n4 — survived 11 rounds — sources: domain_expert — critic: project is already (A)GPL — linking GPL in is fine
    if dependency_license in ('GPL-2.0', 'GPL-3.0') and linking != 'none':
        return 'compatible'
    # n5 — survived 9 rounds — sources: bad_faith_actor, domain_expert — critic: the non-obvious edge a human misses: Apache-2.0 patent terms are incompatible with GPLv2
    if dependency_license == 'Apache-2.0' and project_license == 'GPL-2.0':
        return 'incompatible'
    # n6 — survived 8 rounds — sources: edge_case_hunter — critic: LGPL distinguishes static vs dynamic — static linking into proprietary triggers relinking obligations
    if dependency_license == 'LGPL-3.0' and linking == 'static' and project_license == 'proprietary':
        return 'review_required'
    # gray_zone: LGPL static-linking obligations are satisfiable (provide object files) — counsel can clear it
    # n7 — survived 12 rounds — sources: domain_expert — critic: permissive / weak-copyleft — compatible with attribution (dynamic LGPL/MPL fall here)
    if dependency_license in ('MIT', 'BSD-3-Clause', 'Apache-2.0', 'LGPL-3.0', 'MPL-2.0'):
        return 'compatible'
    # n8 — survived 10 rounds — sources: domain_expert
    if dependency_license == 'proprietary':
        return 'review_required'
    return 'review_required'
