# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-28T16:17:24Z | model: claude-sonnet-4-6 via claude-code-subagents | profile: standard | constraints: v1.0

def can_dog_eat(case: dict) -> str:
    food_item = case.get('food_item')
    food_form = case.get('food_form')
    dog_weight_kg = case.get('dog_weight_kg')
    dog_breed = case.get('dog_breed')
    quantity_grams = case.get('quantity_grams')

    # n1 — survived 2 rounds — sources: bad_faith_actor, overengineering_critic, domain_expert, constraints#1 — critic: collapsed 5 per-toxin branches into one substring membership test — survived overengineering_critic
    if any(tok in (food_item or "").strip().lower() for tok in ("chocolate", "cocoa", "grape", "raisin", "onion", "garlic", "leek", "chive", "shallot", "macadamia", "alcohol", "caffeine", "coffee", "espresso", "tea", "xylitol", "yeast dough", "bread dough", "nutmeg")):
        return 'toxic — never'
    # n2 — survived 2 rounds — sources: domain_expert
    if (food_form or "").strip().lower() == "concentrated":
        return 'toxic — concentrated form raises dose per gram'
    # gray_zone: concentration multiplies toxin/fat dose; treat as unsafe absent food-specific data
    # n3 — survived 2 rounds — sources: edge_case_hunter — critic: kept over overengineering_critic — low-fat/sugar-free PB is the form-based xylitol proxy the source skill missed
    if "peanut butter" in (food_item or "").strip().lower() and (food_form or "").strip().lower() == "low_fat":
        return 'toxic — xylitol risk; check label'
    # gray_zone: safe only if certified xylitol-free
    # n4 — survived 1 rounds — sources: edge_case_hunter, literalist — critic: guard now requires dog_weight_kg > 0 so a falsy/zero weight cannot skip it
    if quantity_grams is not None and dog_weight_kg is not None and dog_weight_kg > 0 and quantity_grams / dog_weight_kg > 50:
        return 'caution — large dose relative to body weight'
    # gray_zone: 50 g/kg is a placeholder threshold — calibrate per food
    # n5 — survived 1 rounds — sources: edge_case_hunter — critic: round-3 fix: a zero/missing weight can't be assessed for dose — fall to unknown, never safe
    if dog_weight_kg is None or dog_weight_kg <= 0:
        return 'unknown — valid dog weight required to assess dose'
    # n6 — survived 2 rounds — sources: domain_expert
    if "peanut butter" in (food_item or "").strip().lower():
        return 'safe — standard formulation, if xylitol-free'
    return 'unknown — verify manually'
