# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-28T16:35:02Z | model: claude (subscription) via claude-code-subagents | profile: standard | constraints: v1.0

def can_dog_eat(case: dict) -> str:
    food_item = case.get('food_item')

    # n1 — survived 2 rounds — sources: constraints#1, domain_expert — critic: toxin set kept expert-sized; nutmeg/yeast-dough deliberately excluded — they return 'no' via the default
    if (food_item or "").strip().lower() in {"chocolate", "cocoa", "grapes", "raisins", "onion", "onions", "garlic", "chives", "leek", "leeks", "xylitol", "alcohol", "ethanol", "caffeine", "coffee", "macadamia", "macadamia nuts"}:
        return 'no — toxic, never feed'
    # n2 — survived 2 rounds — sources: edge_case_hunter — critic: demoted from a hard rule to a gray zone by the overengineering_critic — the source skill ratifies no safe foods
    if (food_item or "").strip().lower() in {"carrot", "carrots", "rice", "chicken", "banana", "blueberries", "green beans", "pumpkin"}:
        return 'yes — safe in moderation'
    # gray_zone: safe-list has no ratified examples in the source skill — ratified by the human at the gate
    # n3 — survived 1 rounds — sources: domain_expert — critic: apple earns its own node — the cyanogenic core/seed caveat can't fold into the generic safe verdict
    if (food_item or "").strip().lower() == "apple":
        return 'yes — flesh only, never core/seeds'
    return 'no — when in doubt, do not feed; verify with a vet'
