# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-28T16:26:58Z | model: claude-opus-4-8 via claude-code-subagents | profile: standard | constraints: v1.0

def can_dog_eat(case: dict) -> str:
    food_item = case.get('food_item')

    # n1 — survived 2 rounds — sources: constraints#H1, domain_expert, ASPCA — critic: expert-sized set; missing labels (nutmeg, raw dough) still return 'no' via default
    if food_item in {"chocolate", "cocoa", "grapes", "raisins", "onion", "onions", "garlic", "chives", "leek", "leeks", "xylitol", "alcohol", "ethanol", "caffeine", "coffee", "macadamia", "macadamia nuts"}:
        return 'no — toxic to dogs, never feed'
    # n2 — survived 2 rounds — sources: user-ratified, domain_expert
    if food_item in {"carrot", "carrots", "plain rice", "cooked rice", "plain chicken", "cooked chicken", "banana", "blueberries", "green beans", "plain pumpkin"}:
        return 'yes — safe in moderation'
    # gray_zone: safe-list has no ratified examples in the source skill; user ratified keeping a conservative whitelist (round 1 gate)
    # n3 — survived 1 rounds — sources: domain_expert — critic: own node justified by cyanogenic seed/core caveat that can't fold into generic safe-in-moderation
    if food_item == "apple":
        return 'yes — apple flesh only; never the core or seeds'
    return 'no — when in doubt, do not feed; verify with a vet'
