"""Deterministic tree → .py exporter, callable from the Claude Code skill.

The subagent-driven loop (see .claude/skills/temper-skills/SKILL.md) produces a
tree as JSON; this turns it into the zero-dependency Python module. No LLM here —
this is the deterministic half of the pipeline.

    python -m temper_skills.export_tree tree.json route.py
    cat tree.json | python -m temper_skills.export_tree - route.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from .tree import DecisionNode, DecisionTree


def _compile(tree: DecisionTree):
    # Inline (not validate.fn_from_tree) to keep this module import-light — the
    # deterministic export path must not pull in the LLM backends.
    ns: dict = {}
    exec(compile(tree.to_source(), f"<{tree.fn_name}>", "exec"), ns)
    return ns[tree.fn_name]


def enrich_proposed(tree: DecisionTree, raw: list[dict]) -> list[dict]:
    """Stamp orchestrator-drafted cases with the tree's own prediction + a 'proposed' tag.

    The subagent loop authors ``input``/``expected``/``rationale``; the *prediction* and the
    un-ratified status are computed here deterministically, so a machine-authored label can
    never masquerade as ground truth (the same trust boundary as the library path)."""
    fn = _compile(tree)
    out: list[dict] = []
    for case in raw:
        try:
            prediction = fn(case["input"])
        except Exception as e:
            prediction = f"ERROR: {type(e).__name__}: {e}"
        record = {
            "input": case["input"],
            "expected": case.get("expected", ""),
            "rationale": case.get("rationale", ""),
            "tree_prediction": prediction,
            # "proposed" = panel-authored, ungated; "resolved" = proposer settled a contested
            # cell (no domain oracle); "ratified" = a human domain owner blessed the label.
            "status": case.get("status", "proposed"),
        }
        if case.get("source"):
            record["source"] = case["source"]
        out.append(record)
    return out


def render_tests(module: str, fn_name: str, enriched: list[dict]) -> str:
    """A committed, runnable pytest that locks the tree's behavior and surfaces open disputes.

    Every case is a regression assertion against the tree's CURRENT output (drift lock). A
    `ratified` case additionally asserts the human-blessed label — if the tree ever disagrees
    with ratified truth, that test fails. A still-`proposed` case whose label differs from the
    tree is an OPEN dispute: emitted as an xfail so it's visible in the run without breaking CI.
    """
    locked, disputes = [], []
    for c in enriched:
        pred = c["tree_prediction"]
        if isinstance(pred, str) and pred.startswith("ERROR"):
            continue
        note = c.get("source", "") + (" — " + c["rationale"] if c.get("rationale") else "")
        open_dispute = c["status"] == "proposed" and c.get("expected") not in ("", pred)
        (disputes if open_dispute else locked).append(
            {"input": c["input"], "expected": pred, "human": c.get("expected"),
             "status": c["status"], "note": note.strip(" —")}
        )

    L = [
        "# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.",
        f"# Behavior lock for {fn_name}: each case asserts the frozen tree's current output.",
        "# Cases are panel-built proposals unless marked 'ratified'; see notes for provenance.",
        "import pytest",
        f"from {module} import {fn_name}",
        "",
        "# (input, expected_output, status, note)",
        "LOCKED = [",
    ]
    for c in locked:
        L.append(f"    ({c['input']!r}, {c['expected']!r}, {c['status']!r}, {c['note']!r}),")
    L += [
        "]",
        "",
        '@pytest.mark.parametrize("case,expected,status,note", LOCKED, '
        'ids=[c[3][:60] for c in LOCKED])',
        f"def test_{fn_name}_behavior(case, expected, status, note):",
        f"    assert {fn_name}(case) == expected",
        "",
    ]
    if disputes:
        L += [
            "# Open disputes: a reviewer proposed a label the tree does not return and no one has",
            "# ratified it. xfail keeps them visible without failing CI; resolve by ratifying the",
            "# tree's answer or changing the tree.",
            "OPEN = [",
        ]
        for c in disputes:
            L.append(f"    ({c['input']!r}, {c['human']!r}, {c['note']!r}),  # tree returns {c['expected']!r}")
        L += [
            "]",
            "",
            '@pytest.mark.parametrize("case,proposed,note", OPEN, ids=[c[2][:60] for c in OPEN])',
            "@pytest.mark.xfail(reason='proposed label not ratified; tree disagrees', strict=False)",
            f"def test_{fn_name}_open_disputes(case, proposed, note):",
            f"    assert {fn_name}(case) == proposed",
            "",
        ]
    return "\n".join(L)


def tree_from_dict(data: dict) -> DecisionTree:
    nodes = [
        DecisionNode(
            condition=n["condition"],
            outcome=n["outcome"],
            rounds_survived=int(n.get("rounds_survived", 1)),
            sources=list(n.get("sources", [])),
            critic_note=n.get("critic_note"),
            gray_zone=n.get("gray_zone"),
        )
        for n in data["nodes"]
    ]
    return DecisionTree(
        nodes=nodes,
        default_outcome=data["default_outcome"],
        features=list(data.get("features", [])),
        fn_name=data.get("fn_name", "decide"),
        model=data.get("model", "claude-code-subagents"),
        profile=data.get("profile", "standard"),
        constraints_version=data.get("constraints_version", "v1.0"),
        include_provenance=bool(data.get("include_provenance", True)),
    )


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    if len(argv) != 2:
        print("usage: python -m temper_skills.export_tree <tree.json|-> <out.py>", file=sys.stderr)
        return 2
    src, out = argv
    raw = sys.stdin.read() if src == "-" else open(src).read()
    data = json.loads(raw)
    tree = tree_from_dict(data)
    tree.export(out)
    print(f"exported {out} ({len(tree.nodes)} nodes)")
    if data.get("proposed_examples"):
        enriched = enrich_proposed(tree, data["proposed_examples"])
        stem = str(Path(out).with_suffix(""))
        side = stem + ".proposed_examples.json"
        Path(side).write_text(json.dumps(enriched, indent=2, ensure_ascii=False))
        print(f"wrote {len(enriched)} proposed test case(s) → {side} "
              f"(proposed, not ratified — review before they gate)")
        test_path = str(Path(out).with_name("test_" + Path(out).name))
        Path(test_path).write_text(render_tests(Path(out).stem, tree.fn_name, enriched))
        print(f"wrote runnable behavior-lock tests → {test_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
