"""Close the loop: emit a tempered skill.md that DELEGATES the decision to the tree.

The original skill asked the model to re-derive the decision from prose every time.
The tempered skill keeps the model's real jobs — turning the request into structured
features, and phrasing the answer — but freezes the *decision* in the deterministic
tree (§2.5: the model extracts and phrases; the tree decides). Deterministic template,
no LLM.

    python -m temper_skills.export_skill tree.json dog_food_checker [skill.tempered.md] [orig_skill.md]
"""

from __future__ import annotations

import re
import sys

from .export_tree import tree_from_dict
from .tree import DecisionTree


def _role_line(original: str | None) -> str:
    if original:
        for line in original.splitlines():
            s = line.strip()
            if re.match(r"(?i)^you are\b", s):
                return s.rstrip(".") + "."
    return "You are an assistant."


def render_tempered_skill(
    tree: DecisionTree,
    module: str,
    fn: str | None = None,
    original_skill_text: str | None = None,
) -> str:
    fn = fn or tree.fn_name
    role = _role_line(original_skill_text)
    feats = tree.features or ["<feature>"]
    gray = [(i, n) for i, n in enumerate(tree.nodes, 1) if n.gray_zone]

    out: list[str] = []
    out.append(f"# {fn} — skill (tempered by temper-skills)")
    out.append("")
    out.append(role)
    out.append("")
    out.append(
        "**The decision is frozen.** Do not re-derive it from prose or your own judgment — "
        f"the routing logic now lives in a deterministic decision tree (`{module}.{fn}`, "
        "zero LLM calls, reviewed and version-controlled). Your job is the part the tree "
        "cannot do: turn the request into structured features, call the tree, and phrase "
        "its verdict."
    )
    out.append("")
    out.append("## How to answer")
    out.append("")
    out.append("1. Extract these structured features from the request:")
    for f in feats:
        out.append(f"   - `{f}`")
    out.append("2. Call the decision tree and treat its result as authoritative:")
    out.append("")
    out.append("   ```python")
    out.append(f"   from {module} import {fn}")
    out.append("   verdict = " + fn + "({" + ", ".join(f'"{f}": {f}' for f in feats) + "})")
    out.append("   ```")
    out.append("3. Relay `verdict` to the user. **Do not override it.** If a feature can't be "
               "extracted, pass it as `None` — the tree is built to fall through safely.")
    out.append("")
    if gray:
        out.append("## Gray zones to surface")
        out.append("")
        out.append("The tree flags these as underdetermined — mention the caveat when the "
                   "answer touches them:")
        for i, n in gray:
            out.append(f"- (n{i}) {n.gray_zone}")
        out.append("")
    out.append("---")
    out.append(
        f"Generated by temper-skills from the original skill · {tree.generated_at} · "
        f"model: {tree.model}. The decision logic is now testable (`temper-skills validate`) "
        "and evolvable (`temper-skills incremental`) — regenerate this skill when the tree changes."
    )
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    if len(argv) < 2:
        print("usage: python -m temper_skills.export_skill <tree.json> <module> "
              "[out.md] [original_skill.md]", file=sys.stderr)
        return 2
    tree_path, module = argv[0], argv[1]
    out = argv[2] if len(argv) > 2 else "skill.tempered.md"
    original = open(argv[3]).read() if len(argv) > 3 else None
    import json
    tree = tree_from_dict(json.loads(open(tree_path).read()))
    md = render_tempered_skill(tree, module, original_skill_text=original)
    with open(out, "w") as f:
        f.write(md)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
