"""Close the loop: emit a tempered skill.md that DELEGATES the decision to the tree.

The original skill asked the model to re-derive the decision from prose every time.
The tempered skill keeps the model's real jobs — turning the request into structured
features, and phrasing the answer — but freezes the *decision* in the deterministic
tree (§2.5: the model extracts and phrases; the tree decides). Deterministic template,
no LLM.

    python -m temper_skills.export_skill tree.json dog_food_checker [skill.tempered.md] [orig_skill.md]
"""

from __future__ import annotations

import re
import sys

from pydantic import BaseModel, Field

from .export_tree import tree_from_dict
from .tree import DecisionTree


def _role_line(original: str | None) -> str:
    if original:
        for line in original.splitlines():
            s = line.strip()
            if re.match(r"(?i)^you are\b", s):
                return s.rstrip(".") + "."
    return "You are an assistant."


def render_tempered_skill(
    tree: DecisionTree,
    module: str,
    fn: str | None = None,
    original_skill_text: str | None = None,
) -> str:
    fn = fn or tree.fn_name
    role = _role_line(original_skill_text)
    feats = tree.features or ["<feature>"]
    gray = [(i, n) for i, n in enumerate(tree.nodes, 1) if n.gray_zone]

    out: list[str] = []
    out.append(f"# {fn} — skill (tempered by temper-skills)")
    out.append("")
    out.append(role)
    out.append("")
    out.append(
        "**The decision is frozen.** Do not re-derive it from prose or your own judgment — "
        f"the routing logic now lives in a deterministic decision tree (`{module}.{fn}`, "
        "zero LLM calls, reviewed and version-controlled). Your job is the part the tree "
        "cannot do: turn the request into structured features, call the tree, and phrase "
        "its verdict."
    )
    out.append("")
    out.append("## How to answer")
    out.append("")
    out.append("1. Extract these structured features from the request:")
    for f in feats:
        out.append(f"   - `{f}`")
    out.append("2. Call the decision tree and treat its result as authoritative:")
    out.append("")
    out.append("   ```python")
    out.append(f"   from {module} import {fn}")
    out.append("   verdict = " + fn + "({" + ", ".join(f'"{f}": {f}' for f in feats) + "})")
    out.append("   ```")
    out.append("3. Relay `verdict` to the user. **Do not override it.** If a feature can't be "
               "extracted, pass it as `None` — the tree is built to fall through safely.")
    out.append("")
    if gray:
        out.append("## Gray zones to surface")
        out.append("")
        out.append("The tree flags these as underdetermined — mention the caveat when the "
                   "answer touches them:")
        for i, n in gray:
            out.append(f"- (n{i}) {n.gray_zone}")
        out.append("")
    out.append("---")
    out.append(
        f"Generated by temper-skills from the original skill · {tree.generated_at} · "
        f"model: {tree.model}. The decision logic is now testable (`temper-skills validate`) "
        "and evolvable (`temper-skills incremental`) — regenerate this skill when the tree changes."
    )
    return "\n".join(out) + "\n"


class WovenSkill(BaseModel):
    markdown: str = Field(description="The complete rewritten skill.md, ready to save.")


WEAVE_SYSTEM = (
    "You revise an agent's skill/prompt so it DELEGATES its decision to a frozen, "
    "deterministic decision tree, while preserving the skill's voice, role, and any "
    "instructions unrelated to the decision. You never invent new policy or new rules — "
    "the tree is the single source of the decision now."
)


def _render_nodes(tree: DecisionTree) -> str:
    lines = [f"  if ({n.condition}) -> {n.outcome}" for n in tree.nodes]
    lines.append(f"  default -> {tree.default_outcome}")
    return "\n".join(lines)


def module_call(module: str, fn: str, feats: list[str]) -> str:
    return f'{fn}({{{", ".join(f"{f!r}: {f}" for f in feats)}}})'


def weave_tempered_skill(
    tree: DecisionTree,
    module: str,
    original_skill_text: str,
    backend,
    fn: str | None = None,
) -> str:
    """LLM-rewrite the original skill to delegate to the tree (preserves voice).

    Falls back to the deterministic template at the call site if the backend fails.
    """
    fn = fn or tree.fn_name
    feats = tree.features or ["<feature>"]
    gray = [n.gray_zone for n in tree.nodes if n.gray_zone]
    user = (
        "ORIGINAL SKILL (preserve its voice, role, and any non-decision instructions):\n"
        f"{original_skill_text}\n\n"
        "The decision logic has been compiled into this deterministic tree (do NOT restate "
        f"its rules as prose — call it):\n{_render_nodes(tree)}\n\n"
        "Rewrite the skill so it DELEGATES the decision to the tree. Requirements:\n"
        f"- Keep the original role and voice; drop only the prose that re-derived the decision.\n"
        f"- Instruct the agent to (1) extract the structured features {feats} from the request, "
        f"(2) call `from {module} import {fn}` then `verdict = {module_call(module, fn, feats)}`, "
        f"(3) relay the verdict and NEVER override or re-derive it; pass a missing feature as None.\n"
        + ("- Surface these gray zones as caveats when relevant: " + "; ".join(gray) + "\n" if gray else "")
        + "- Do NOT invent new rules, foods, categories, or thresholds — only re-route to the tree.\n"
        "Return the COMPLETE skill.md as markdown, ready to save, with no preamble."
    )
    return backend.complete(WEAVE_SYSTEM, user, WovenSkill).markdown


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    if len(argv) < 2:
        print("usage: python -m temper_skills.export_skill <tree.json> <module> "
              "[out.md] [original_skill.md]", file=sys.stderr)
        return 2
    tree_path, module = argv[0], argv[1]
    out = argv[2] if len(argv) > 2 else "skill.tempered.md"
    original = open(argv[3]).read() if len(argv) > 3 else None
    import json
    tree = tree_from_dict(json.loads(open(tree_path).read()))
    md = render_tempered_skill(tree, module, original_skill_text=original)
    with open(out, "w") as f:
        f.write(md)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
