"""The deliverable: a deterministic decision tree that exports to plain Python."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone


@dataclass
class DecisionNode:
    """One branch of the tree, carrying its provenance (§4.4)."""

    condition: str          # a Python boolean expression over the feature names
    outcome: str            # the value returned when the condition holds
    rounds_survived: int = 0
    sources: list[str] = field(default_factory=list)
    critic_note: str | None = None      # overengineering_critic verdict, if any
    gray_zone: str | None = None        # flagged ambiguity near this node


@dataclass
class DecisionTree:
    """An ordered list of branches plus a default outcome and run metadata.

    Conditions reference feature names directly (``food_item == "chocolate"``).
    The exported function takes one dict and binds each feature as a local, so
    no condition rewriting is needed — what the loop reasons about is what runs.
    """

    nodes: list[DecisionNode]
    default_outcome: str
    features: list[str] = field(default_factory=list)
    fn_name: str = "decide"
    arg_name: str = "case"
    model: str = "unknown"
    profile: str = "standard"
    constraints_version: str = "v1.0"
    generated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    )
    include_provenance: bool = True
    # Result of checking the final tree against the ratified examples, if any were
    # provided. Metadata only — not emitted into the exported source.
    example_report: "object | None" = None
    # Discriminating test cases the loop drafted for its gray zones, each
    # {input, expected, rationale, tree_prediction, status: "proposed"}. PROPOSALS
    # for human ratification — they do not gate CI until ratified. Metadata only.
    proposed_examples: "list | None" = None

    def to_source(self) -> str:
        """Render the tree as a zero-dependency Python module."""
        lines: list[str] = []
        lines.append("# Auto-generated by temper-skills — zero LLM calls at inference")
        lines.append(
            f"# generated_at: {self.generated_at} | model: {self.model} "
            f"| profile: {self.profile} | constraints: {self.constraints_version}"
        )
        if not self.include_provenance:
            lines.append("# quick profile — draft output, no provenance. Do not ship.")
        lines.append("")
        lines.append(f"def {self.fn_name}({self.arg_name}: dict) -> str:")
        for feat in self.features:
            lines.append(f"    {feat} = {self.arg_name}.get({feat!r})")
        if self.features:
            lines.append("")

        if not self.nodes:
            lines.append(f"    return {self._outcome(self.default_outcome)}")
            return "\n".join(lines) + "\n"

        for i, node in enumerate(self.nodes, start=1):
            if self.include_provenance:
                prov = f"    # n{i} — survived {node.rounds_survived} rounds"
                if node.sources:
                    prov += f" — sources: {', '.join(node.sources)}"
                if node.critic_note:
                    prov += f" — critic: {node.critic_note}"
                lines.append(prov)
            lines.append(f"    if {node.condition}:")
            lines.append(f"        return {self._outcome(node.outcome)}")
            if self.include_provenance and node.gray_zone:
                lines.append(f"    # gray_zone: {node.gray_zone}")
        lines.append(f"    return {self._outcome(self.default_outcome)}")
        return "\n".join(lines) + "\n"

    def export(self, path: str) -> str:
        src = self.to_source()
        with open(path, "w") as f:
            f.write(src)
        return src

    @staticmethod
    def _outcome(outcome: str) -> str:
        return repr(outcome)
