# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-07-01T12:45:19Z | model: claude-opus-4-8 via temper-skills | profile: standard | constraints: v1.0

def can_dog_eat(case: dict) -> str:
    food_item = case.get('food_item')
    food_form = case.get('food_form')
    dog_weight_kg = case.get('dog_weight_kg')
    dog_breed = case.get('dog_breed')
    quantity_grams = case.get('quantity_grams')

    # critic: expert-sized set; unlisted toxins still return 'no' via the default
    if (food_item or "").strip().lower() in {"chocolate", "cocoa", "grapes", "raisins", "onion", "onions", "garlic", "chives", "leek", "leeks", "xylitol", "alcohol", "ethanol", "caffeine", "coffee", "macadamia", "macadamia nuts"}:
        return 'no — toxic to dogs, never feed'
    if (food_form or "").strip().lower() == "concentrated":
        return 'no — concentrated form multiplies toxin and fat dose per gram'
    # gray_zone: concentrated/powdered forms are unsafe absent food-specific data
    # critic: kept over overengineering_critic — the low-fat form is the xylitol proxy the source skill missed
    if "peanut butter" in (food_item or "").strip().lower() and (food_form or "").strip().lower() == "low_fat":
        return 'no — low-fat/sugar-free peanut butter may contain xylitol; check the label'
    # critic: guard requires dog_weight_kg > 0 so a falsy/zero weight cannot skip it
    if quantity_grams is not None and dog_weight_kg is not None and dog_weight_kg > 0 and quantity_grams / dog_weight_kg > 50:
        return 'caution — large dose relative to body weight'
    # gray_zone: 50 g/kg is a placeholder threshold — calibrate per food
    # critic: a zero/missing weight can't be dose-assessed — fall to unknown, never safe
    if quantity_grams is not None and (dog_weight_kg is None or dog_weight_kg <= 0):
        return 'unknown — a valid dog weight is required to assess this quantity'
    if "peanut butter" in (food_item or "").strip().lower():
        return 'yes — standard peanut butter is safe in moderation, if xylitol-free'
    # critic: demoted from a hard rule to a gray zone — the source skill ratifies no safe foods
    if (food_item or "").strip().lower() in {"carrot", "carrots", "rice", "chicken", "banana", "blueberries", "green beans", "pumpkin"}:
        return 'yes — safe in moderation'
    # gray_zone: safe-list has no ratified examples in the source skill; user ratified a conservative whitelist at the gate
    # critic: own node — the cyanogenic core/seed caveat can't fold into generic safe-in-moderation
    if (food_item or "").strip().lower() == "apple":
        return 'yes — apple flesh only; never the core or seeds'
    return 'no — when in doubt, do not feed; verify with a vet'
