# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Ratified-truth tests for can_dog_eat: assert the tree matches HUMAN-blessed labels.
# This file CAN fail — a red test here means the tree contradicts ratified ground truth.
# Comparison is leading-label (temper-skills' label_match): a descriptive outcome like
# 'no — toxic' honors the ratified label 'no'.
import pytest
from can_dog_eat import can_dog_eat

def _label(s):
    head = str(s).strip().split()[0] if str(s).strip() else ''
    return head.lower().rstrip(':,.—-')

# (input, ratified_label, note)
RATIFIED = [
    ({'food_item': 'chocolate', 'food_form': 'standard', 'dog_weight_kg': 10}, 'no', 'ratified'),
    ({'food_item': 'grapes', 'food_form': 'raw', 'dog_weight_kg': 20}, 'no', 'ratified'),
    ({'food_item': 'onion', 'food_form': 'cooked', 'dog_weight_kg': 12}, 'no', 'ratified'),
    ({'food_item': 'macadamia', 'food_form': 'standard', 'dog_weight_kg': 30}, 'no', 'ratified'),
    ({'food_item': 'xylitol', 'food_form': 'standard', 'dog_weight_kg': 8}, 'no', 'ratified'),
    ({'food_item': 'garlic powder', 'food_form': 'concentrated', 'dog_weight_kg': 10}, 'no', 'ratified'),
    ({'food_item': 'peanut butter', 'food_form': 'low_fat', 'dog_weight_kg': 10}, 'no', 'ratified'),
    ({'food_item': 'peanut butter', 'food_form': 'standard', 'dog_weight_kg': 10}, 'yes', 'ratified'),
    ({'food_item': 'carrot', 'food_form': 'raw', 'dog_weight_kg': 8, 'quantity_grams': 50}, 'yes', 'ratified'),
    ({'food_item': 'carrot', 'food_form': 'raw', 'dog_weight_kg': 8, 'quantity_grams': 600}, 'caution', 'ratified'),
    ({'food_item': 'chicken', 'food_form': 'cooked', 'dog_weight_kg': 15}, 'yes', 'ratified'),
    ({'food_item': 'banana', 'food_form': 'standard', 'dog_weight_kg': 5}, 'yes', 'ratified'),
    ({'food_item': 'blueberries', 'food_form': 'raw', 'dog_weight_kg': 6}, 'yes', 'ratified'),
    ({'food_item': 'pumpkin', 'food_form': 'cooked', 'dog_weight_kg': 9}, 'yes', 'ratified'),
    ({'food_item': 'apple', 'food_form': 'raw', 'dog_weight_kg': 10}, 'yes', 'ratified'),
    ({'food_item': 'peanut butter', 'food_form': 'standard', 'dog_weight_kg': 0, 'quantity_grams': 100}, 'unknown', 'ratified'),
    ({'food_item': 'rice', 'food_form': 'cooked', 'dog_weight_kg': 4, 'quantity_grams': 400}, 'caution', 'ratified'),
    ({'food_item': 'kibble', 'food_form': 'standard', 'dog_weight_kg': 10}, 'no', 'ratified'),
    ({'food_item': 'Chocolate', 'food_form': 'standard', 'dog_weight_kg': 10}, 'no', 'ratified'),
    ({'food_item': '  grapes  ', 'food_form': 'standard', 'dog_weight_kg': 10}, 'no', 'ratified'),
    ({'food_item': 'tofu', 'food_form': 'raw', 'dog_weight_kg': 10}, 'no', 'ratified'),
]

@pytest.mark.parametrize("case,expected,note", RATIFIED, ids=[c[2][:60] for c in RATIFIED])
def test_can_dog_eat_ratified(case, expected, note):
    assert _label(can_dog_eat(case)) == _label(expected)
