# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Behavior lock for can_dog_eat: each case asserts the tree's CURRENT output.
# Always green by construction — a failure here means the tree drifted (a real regression).
# Debates are NOT here; they live in the .validation.jsonl dataset.
import pytest
from can_dog_eat import can_dog_eat

# (input, tree_output, status, note)
LOCKED = [
    ({'food_item': 'chocolate', 'food_form': 'standard', 'dog_weight_kg': 10}, 'no — toxic to dogs, never feed', 'ratified', 'ratified'),
    ({'food_item': 'grapes', 'food_form': 'raw', 'dog_weight_kg': 20}, 'no — toxic to dogs, never feed', 'ratified', 'ratified'),
    ({'food_item': 'onion', 'food_form': 'cooked', 'dog_weight_kg': 12}, 'no — toxic to dogs, never feed', 'ratified', 'ratified'),
    ({'food_item': 'macadamia', 'food_form': 'standard', 'dog_weight_kg': 30}, 'no — toxic to dogs, never feed', 'ratified', 'ratified'),
    ({'food_item': 'xylitol', 'food_form': 'standard', 'dog_weight_kg': 8}, 'no — toxic to dogs, never feed', 'ratified', 'ratified'),
    ({'food_item': 'garlic powder', 'food_form': 'concentrated', 'dog_weight_kg': 10}, 'no — concentrated form multiplies toxin and fat dose per gram', 'ratified', 'ratified'),
    ({'food_item': 'peanut butter', 'food_form': 'low_fat', 'dog_weight_kg': 10}, 'no — low-fat/sugar-free peanut butter may contain xylitol; check the label', 'ratified', 'ratified'),
    ({'food_item': 'peanut butter', 'food_form': 'standard', 'dog_weight_kg': 10}, 'yes — standard peanut butter is safe in moderation, if xylitol-free', 'ratified', 'ratified'),
    ({'food_item': 'carrot', 'food_form': 'raw', 'dog_weight_kg': 8, 'quantity_grams': 50}, 'yes — safe in moderation', 'ratified', 'ratified'),
    ({'food_item': 'carrot', 'food_form': 'raw', 'dog_weight_kg': 8, 'quantity_grams': 600}, 'caution — large dose relative to body weight', 'ratified', 'ratified'),
    ({'food_item': 'chicken', 'food_form': 'cooked', 'dog_weight_kg': 15}, 'yes — safe in moderation', 'ratified', 'ratified'),
    ({'food_item': 'banana', 'food_form': 'standard', 'dog_weight_kg': 5}, 'yes — safe in moderation', 'ratified', 'ratified'),
    ({'food_item': 'blueberries', 'food_form': 'raw', 'dog_weight_kg': 6}, 'yes — safe in moderation', 'ratified', 'ratified'),
    ({'food_item': 'pumpkin', 'food_form': 'cooked', 'dog_weight_kg': 9}, 'yes — safe in moderation', 'ratified', 'ratified'),
    ({'food_item': 'apple', 'food_form': 'raw', 'dog_weight_kg': 10}, 'yes — apple flesh only; never the core or seeds', 'ratified', 'ratified'),
    ({'food_item': 'peanut butter', 'food_form': 'standard', 'dog_weight_kg': 0, 'quantity_grams': 100}, 'unknown — a valid dog weight is required to assess this quantity', 'ratified', 'ratified'),
    ({'food_item': 'rice', 'food_form': 'cooked', 'dog_weight_kg': 4, 'quantity_grams': 400}, 'caution — large dose relative to body weight', 'ratified', 'ratified'),
    ({'food_item': 'kibble', 'food_form': 'standard', 'dog_weight_kg': 10}, 'no — when in doubt, do not feed; verify with a vet', 'ratified', 'ratified'),
    ({'food_item': 'Chocolate', 'food_form': 'standard', 'dog_weight_kg': 10}, 'no — toxic to dogs, never feed', 'ratified', 'ratified'),
    ({'food_item': '  grapes  ', 'food_form': 'standard', 'dog_weight_kg': 10}, 'no — toxic to dogs, never feed', 'ratified', 'ratified'),
    ({'food_item': 'tofu', 'food_form': 'raw', 'dog_weight_kg': 10}, 'no — when in doubt, do not feed; verify with a vet', 'ratified', 'ratified'),
]

@pytest.mark.parametrize("case,expected,status,note", LOCKED, ids=[c[3][:60] for c in LOCKED])
def test_can_dog_eat_behavior(case, expected, status, note):
    assert can_dog_eat(case) == expected
