# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-07-01T09:58:17Z | model: claude-opus-4-8 via claude-code-subagents | profile: standard | constraints: v1.0

def decide_vet(case: dict) -> str:
    symptom = case.get('symptom')
    severity = case.get('severity')
    duration_hours = case.get('duration_hours')
    age_years = case.get('age_years')

    if (severity or '').strip().lower() == 'severe':
        return 'vet_urgent'
    if (symptom or '').strip().lower() == 'none':
        return 'monitor_home'
    if duration_hours is not None and duration_hours >= 48:
        return 'vet_soon'
    if age_years is not None and (age_years < 1 or age_years > 8):
        return 'vet_call'
    # gray_zone: puppy(<1)/senior(>8) lower threshold applies even to a mild & brief symptom, so they never reach the monitor branch.
    # critic: the 0 <= lower bound (added r2) rejects negative/garbage durations so they can't masquerade as 'brief' and yield a falsely reassuring monitor_home.
    if (severity or '').strip().lower() == 'mild' and duration_hours is not None and 0 <= duration_hours < 24:
        return 'monitor_home'
    return 'vet_call'
