# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-07-01T09:58:17Z | model: claude-opus-4-8 via claude-code-subagents | profile: standard | constraints: v1.0

def decide_walk(case: dict) -> str:
    hours_since_last_walk = case.get('hours_since_last_walk')
    weather = case.get('weather')
    temperature_c = case.get('temperature_c')
    dog_energy = case.get('dog_energy')
    owner_available = case.get('owner_available')
    is_late = case.get('is_late')

    if (weather or '').strip().lower() == 'storm' or (temperature_c is not None and temperature_c > 30) or (temperature_c is None and (weather or '').strip().lower() == 'heat'):
        return 'toilet_break_only'
    # gray_zone: measured temperature_c overrides the label — >30°C always skips; the 'heat' label only skips when temperature is unmeasured (None). snow/cold carry no branch (source is silent) and degrade to normal_walk.
    if owner_available is False and is_late is not True:
        return 'postpone_walk'
    # gray_zone: late + owner-away falls through to a walk; source says don't postpone when late but never says who walks.
    if hours_since_last_walk is not None and hours_since_last_walk > 4 and (dog_energy or '').strip().lower() == 'high':
        return 'walk_now'
    return 'normal_walk'
