# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-28T21:00:49Z | model: claude-opus-4-8 via temper-skills | profile: audit-grade | constraints: v1.0

def assess_ankle(case: dict) -> str:
    pain_malleolar_zone = case.get('pain_malleolar_zone')
    bone_tenderness_lateral_malleolus = case.get('bone_tenderness_lateral_malleolus')
    bone_tenderness_medial_malleolus = case.get('bone_tenderness_medial_malleolus')
    can_bear_weight = case.get('can_bear_weight')
    visible_deformity = case.get('visible_deformity')
    sprain_grade = case.get('sprain_grade')
    hours_since_injury = case.get('hours_since_injury')
    age_years = case.get('age_years')
    patient_profile = case.get('patient_profile')

    # n1 — survived 15 rounds — sources: constraints#H1, domain_expert — critic: gross deformity → emergency, checked before anything else
    if visible_deformity is True:
        return 'urgent_care'
    # n2 — survived 14 rounds — sources: domain_expert, Ottawa Ankle Rules, examples#2 — critic: the Ottawa Ankle Rule — 5 interacting criteria that rule fracture in/out; this is the combinatorics a flat 'is it broken?' check misses
    if pain_malleolar_zone is True and (bone_tenderness_lateral_malleolus is True or bone_tenderness_medial_malleolus is True or can_bear_weight is False):
        return 'seek_imaging'
    # gray_zone: Ottawa Rules are validated for ages ~18–55; outside that, escalate (handled below)
    # n3 — survived 11 rounds — sources: edge_case_hunter — critic: can't bear weight but Ottawa-negative (no malleolar pain) — still warrants in-person assessment
    if can_bear_weight is False:
        return 'see_clinician'
    # n4 — survived 9 rounds — sources: domain_expert, edge_case_hunter — critic: Ottawa Rules less validated under 18 / over 55 — be conservative
    if age_years is not None and (age_years < 18 or age_years > 55):
        return 'see_clinician'
    # n5 — survived 10 rounds — sources: domain_expert
    if sprain_grade == "severe":
        return 'see_clinician'
    # n6 — survived 13 rounds — sources: domain_expert, PEACE & LOVE (2019) — critic: OH-MERDE: the source skill said RICE + complete rest + heavy icing — that's outdated since ~2012. Acute phase is PEACE: Protect, Elevate, Avoid anti-inflammatory modalities incl. prolonged ICE (it slows healing), Compress, Educate — with early protected loading, NOT complete rest
    if hours_since_injury is not None and hours_since_injury <= 72:
        return 'police_acute'
    # gray_zone: ice for symptom relief is fine briefly; the harm is prolonged/aggressive icing and immobilization
    # n7 — survived 12 rounds — sources: domain_expert, PEACE & LOVE (2019) — critic: subacute phase is LOVE: Load (progressive), Optimism, Vascularisation (gentle cardio), Exercise — mobilize, don't rest
    if hours_since_injury is not None and hours_since_injury > 72:
        return 'police_subacute'
    return 'see_clinician'
