# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Behavior lock for assess_license: each case asserts the tree's CURRENT output.
# Always green by construction — a failure here means the tree drifted (a real regression).
# Debates are NOT here; they live in the .validation.jsonl dataset.
import pytest
from assess_license import assess_license

# (input, tree_output, status, note)
LOCKED = [
    ({'project_license': 'MIT', 'dependency_license': 'MIT', 'linking': 'dynamic', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'GPL-3.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'project_must_be_gpl', 'ratified', 'ratified'),
    ({'project_license': 'GPL-3.0', 'dependency_license': 'GPL-2.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'AGPL-3.0', 'linking': 'dynamic', 'distributing': True, 'modified_dependency': False}, 'must_offer_source', 'ratified', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'GPL-3.0', 'linking': 'static', 'distributing': False, 'modified_dependency': False}, 'ok_internal_use', 'ratified', 'ratified'),
    ({'project_license': 'GPL-2.0', 'dependency_license': 'Apache-2.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'incompatible', 'ratified', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'LGPL-3.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'review_required', 'ratified', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'LGPL-3.0', 'linking': 'dynamic', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified', 'ratified'),
    ({'project_license': 'MIT', 'dependency_license': 'Apache-2.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'proprietary', 'linking': 'none', 'distributing': True, 'modified_dependency': False}, 'review_required', 'ratified', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'GPL-3.0', 'linking': 'none', 'distributing': True, 'modified_dependency': False}, 'review_required', 'ratified', 'ratified'),
    ({'project_license': 'MIT', 'dependency_license': 'BSD-3-Clause', 'linking': 'dynamic', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified', 'ratified'),
    ({'project_license': 'AGPL-3.0', 'dependency_license': 'GPL-3.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'MPL-2.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'GPL-2.0', 'linking': 'dynamic', 'distributing': True, 'modified_dependency': False}, 'project_must_be_gpl', 'ratified', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'AGPL-3.0', 'linking': 'none', 'distributing': True, 'modified_dependency': False}, 'must_offer_source', 'ratified', 'ratified'),
    ({'project_license': 'MIT', 'dependency_license': 'MIT', 'linking': 'dynamic', 'distributing': None, 'modified_dependency': False}, 'ok_internal_use', 'ratified', 'ratified'),
    ({'project_license': 'Apache-2.0', 'dependency_license': 'GPL-3.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'project_must_be_gpl', 'ratified', 'ratified'),
]

@pytest.mark.parametrize("case,expected,status,note", LOCKED, ids=[c[3][:60] for c in LOCKED])
def test_assess_license_behavior(case, expected, status, note):
    assert assess_license(case) == expected
