# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Ratified-truth tests for assess_license: assert the tree matches HUMAN-blessed labels.
# This file CAN fail — a red test here means the tree contradicts ratified ground truth.
# Comparison is leading-label (temper-skills' label_match): a descriptive outcome like
# 'no — toxic' honors the ratified label 'no'.
import pytest
from assess_license import assess_license

def _label(s):
    head = str(s).strip().split()[0] if str(s).strip() else ''
    return head.lower().rstrip(':,.—-')

# (input, ratified_label, note)
RATIFIED = [
    ({'project_license': 'MIT', 'dependency_license': 'MIT', 'linking': 'dynamic', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'GPL-3.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'project_must_be_gpl', 'ratified'),
    ({'project_license': 'GPL-3.0', 'dependency_license': 'GPL-2.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'AGPL-3.0', 'linking': 'dynamic', 'distributing': True, 'modified_dependency': False}, 'must_offer_source', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'GPL-3.0', 'linking': 'static', 'distributing': False, 'modified_dependency': False}, 'ok_internal_use', 'ratified'),
    ({'project_license': 'GPL-2.0', 'dependency_license': 'Apache-2.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'incompatible', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'LGPL-3.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'review_required', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'LGPL-3.0', 'linking': 'dynamic', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified'),
    ({'project_license': 'MIT', 'dependency_license': 'Apache-2.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'proprietary', 'linking': 'none', 'distributing': True, 'modified_dependency': False}, 'review_required', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'GPL-3.0', 'linking': 'none', 'distributing': True, 'modified_dependency': False}, 'review_required', 'ratified'),
    ({'project_license': 'MIT', 'dependency_license': 'BSD-3-Clause', 'linking': 'dynamic', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified'),
    ({'project_license': 'AGPL-3.0', 'dependency_license': 'GPL-3.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'MPL-2.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'compatible', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'GPL-2.0', 'linking': 'dynamic', 'distributing': True, 'modified_dependency': False}, 'project_must_be_gpl', 'ratified'),
    ({'project_license': 'proprietary', 'dependency_license': 'AGPL-3.0', 'linking': 'none', 'distributing': True, 'modified_dependency': False}, 'must_offer_source', 'ratified'),
    ({'project_license': 'MIT', 'dependency_license': 'MIT', 'linking': 'dynamic', 'distributing': None, 'modified_dependency': False}, 'ok_internal_use', 'ratified'),
    ({'project_license': 'Apache-2.0', 'dependency_license': 'GPL-3.0', 'linking': 'static', 'distributing': True, 'modified_dependency': False}, 'project_must_be_gpl', 'ratified'),
]

@pytest.mark.parametrize("case,expected,note", RATIFIED, ids=[c[2][:60] for c in RATIFIED])
def test_assess_license_ratified(case, expected, note):
    assert _label(assess_license(case)) == _label(expected)
