# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Behavior lock for can_i_park: each case asserts the tree's CURRENT output.
# Always green by construction — a failure here means the tree drifted (a real regression).
# Debates are NOT here; they live in the .validation.jsonl dataset.
import pytest
from can_i_park import can_i_park

# (input, tree_output, status, note)
LOCKED = [
    ({'zone_type': 'no_stopping', 'day': 'monday', 'hour': 10, 'is_public_holiday': False, 'has_resident_permit': False}, 'prohibited', 'ratified', 'ratified'),
    ({'zone_type': 'no_stopping', 'day': 'sunday', 'hour': 3, 'is_public_holiday': True, 'has_resident_permit': True}, 'prohibited', 'ratified', 'ratified'),
    ({'zone_type': 'unrestricted', 'day': 'tuesday', 'hour': 11, 'is_public_holiday': False, 'has_resident_permit': False}, 'no_parking_street_cleaning', 'ratified', 'ratified'),
    ({'zone_type': 'unrestricted', 'day': 'tuesday', 'hour': 11, 'is_public_holiday': True, 'has_resident_permit': False}, 'free', 'ratified', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'friday', 'hour': 12, 'is_public_holiday': False, 'has_resident_permit': True}, 'no_parking_street_cleaning', 'ratified', 'ratified'),
    ({'zone_type': 'metered', 'day': 'tuesday', 'hour': 11, 'is_public_holiday': False, 'has_resident_permit': False}, 'no_parking_street_cleaning', 'ratified', 'ratified'),
    ({'zone_type': 'metered', 'day': 'monday', 'hour': 10, 'is_public_holiday': False, 'has_resident_permit': False}, 'pay_and_display_2h', 'ratified', 'ratified'),
    ({'zone_type': 'metered', 'day': 'saturday', 'hour': 14, 'is_public_holiday': False, 'has_resident_permit': False}, 'pay_and_display_2h', 'ratified', 'ratified'),
    ({'zone_type': 'metered', 'day': 'sunday', 'hour': 12, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified', 'ratified'),
    ({'zone_type': 'metered', 'day': 'monday', 'hour': 10, 'is_public_holiday': True, 'has_resident_permit': False}, 'free', 'ratified', 'ratified'),
    ({'zone_type': 'metered', 'day': 'monday', 'hour': 18, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified', 'ratified'),
    ({'zone_type': 'metered', 'day': 'monday', 'hour': 8, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'monday', 'hour': 9, 'is_public_holiday': False, 'has_resident_permit': False}, 'permit_required', 'ratified', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'monday', 'hour': 9, 'is_public_holiday': False, 'has_resident_permit': True}, 'free', 'ratified', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'saturday', 'hour': 10, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'monday', 'hour': 20, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'wednesday', 'hour': 19, 'is_public_holiday': False, 'has_resident_permit': False}, 'permit_required', 'ratified', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'monday', 'hour': 9, 'is_public_holiday': True, 'has_resident_permit': False}, 'free', 'ratified', 'ratified'),
    ({'zone_type': 'unrestricted', 'day': 'monday', 'hour': 3, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'friday', 'hour': 13, 'is_public_holiday': False, 'has_resident_permit': False}, 'permit_required', 'ratified', 'ratified'),
]

@pytest.mark.parametrize("case,expected,status,note", LOCKED, ids=[c[3][:60] for c in LOCKED])
def test_can_i_park_behavior(case, expected, status, note):
    assert can_i_park(case) == expected
