# Auto-generated by temper-skills — DO NOT EDIT. Regenerate with export_tree.
# Ratified-truth tests for can_i_park: assert the tree matches HUMAN-blessed labels.
# This file CAN fail — a red test here means the tree contradicts ratified ground truth.
# Comparison is leading-label (temper-skills' label_match): a descriptive outcome like
# 'no — toxic' honors the ratified label 'no'.
import pytest
from can_i_park import can_i_park

def _label(s):
    head = str(s).strip().split()[0] if str(s).strip() else ''
    return head.lower().rstrip(':,.—-')

# (input, ratified_label, note)
RATIFIED = [
    ({'zone_type': 'no_stopping', 'day': 'monday', 'hour': 10, 'is_public_holiday': False, 'has_resident_permit': False}, 'prohibited', 'ratified'),
    ({'zone_type': 'no_stopping', 'day': 'sunday', 'hour': 3, 'is_public_holiday': True, 'has_resident_permit': True}, 'prohibited', 'ratified'),
    ({'zone_type': 'unrestricted', 'day': 'tuesday', 'hour': 11, 'is_public_holiday': False, 'has_resident_permit': False}, 'no_parking_street_cleaning', 'ratified'),
    ({'zone_type': 'unrestricted', 'day': 'tuesday', 'hour': 11, 'is_public_holiday': True, 'has_resident_permit': False}, 'free', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'friday', 'hour': 12, 'is_public_holiday': False, 'has_resident_permit': True}, 'no_parking_street_cleaning', 'ratified'),
    ({'zone_type': 'metered', 'day': 'tuesday', 'hour': 11, 'is_public_holiday': False, 'has_resident_permit': False}, 'no_parking_street_cleaning', 'ratified'),
    ({'zone_type': 'metered', 'day': 'monday', 'hour': 10, 'is_public_holiday': False, 'has_resident_permit': False}, 'pay_and_display_2h', 'ratified'),
    ({'zone_type': 'metered', 'day': 'saturday', 'hour': 14, 'is_public_holiday': False, 'has_resident_permit': False}, 'pay_and_display_2h', 'ratified'),
    ({'zone_type': 'metered', 'day': 'sunday', 'hour': 12, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified'),
    ({'zone_type': 'metered', 'day': 'monday', 'hour': 10, 'is_public_holiday': True, 'has_resident_permit': False}, 'free', 'ratified'),
    ({'zone_type': 'metered', 'day': 'monday', 'hour': 18, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified'),
    ({'zone_type': 'metered', 'day': 'monday', 'hour': 8, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'monday', 'hour': 9, 'is_public_holiday': False, 'has_resident_permit': False}, 'permit_required', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'monday', 'hour': 9, 'is_public_holiday': False, 'has_resident_permit': True}, 'free', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'saturday', 'hour': 10, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'monday', 'hour': 20, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'wednesday', 'hour': 19, 'is_public_holiday': False, 'has_resident_permit': False}, 'permit_required', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'monday', 'hour': 9, 'is_public_holiday': True, 'has_resident_permit': False}, 'free', 'ratified'),
    ({'zone_type': 'unrestricted', 'day': 'monday', 'hour': 3, 'is_public_holiday': False, 'has_resident_permit': False}, 'free', 'ratified'),
    ({'zone_type': 'residential_permit', 'day': 'friday', 'hour': 13, 'is_public_holiday': False, 'has_resident_permit': False}, 'permit_required', 'ratified'),
]

@pytest.mark.parametrize("case,expected,note", RATIFIED, ids=[c[2][:60] for c in RATIFIED])
def test_can_i_park_ratified(case, expected, note):
    assert _label(can_i_park(case)) == _label(expected)
