# Auto-generated by temper-skills — zero LLM calls at inference
# generated_at: 2026-06-28T19:30:15Z | model: claude-opus-4-8 via temper-skills | profile: standard | constraints: v1.0

def route_ticket(case: dict) -> str:
    priority = case.get('priority')
    security_score = case.get('security_score')
    customer_tier = case.get('customer_tier')
    category = case.get('category')
    sla_breached = case.get('sla_breached')

    # n1 — survived 12 rounds — sources: constraints#H1 — critic: hard constraint — overrides every routing rule below
    if security_score is not None and security_score > 0.95:
        return 'human_review'
    # n2 — survived 11 rounds — sources: domain_expert, examples#2
    if category == "security" or (security_score is not None and security_score > 0.8):
        return 'escalate_security'
    # gray_zone: the 0.8 score threshold is a tuned cut — calibrate against your incident data
    # n3 — survived 9 rounds — sources: domain_expert — critic: urgent escalates regardless of tier — survived bad_faith_actor
    if priority == "urgent":
        return 'escalate_urgent'
    # n4 — survived 8 rounds — sources: edge_case_hunter, examples#5 — critic: the priority×tier interaction the source prose only implied
    if priority == "high" and customer_tier in ("pro", "enterprise"):
        return 'escalate_urgent'
    # n5 — survived 7 rounds — sources: edge_case_hunter, examples#7 — critic: sla×tier interaction — a breached SLA escalates only for paying tiers
    if sla_breached is True and customer_tier != "free":
        return 'escalate_urgent'
    # n6 — survived 6 rounds — sources: domain_expert
    if category == "billing":
        return 'route_billing'
    # n7 — survived 6 rounds — sources: domain_expert — critic: account/feature_request/other collapse into the default — not enumerated (overengineering_critic)
    if category == "bug":
        return 'route_engineering'
    return 'route_default'
